# Generated by Django 2.1.2 on 2018-10-13 17:08

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='', max_length=512)),
                ('icon', models.ImageField(default='icons/default.png', upload_to='icons/groups/')),
                ('is_checked', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=512)),
                ('icon', models.ImageField(default='icons/default.png', upload_to='icons/groups/')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='groups.Group')),
            ],
            options={
                'verbose_name_plural': 'groups',
            },
        ),
        migrations.AddField(
            model_name='element',
            name='group',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
    ]
