# Generated by Django 2.1.2 on 2018-10-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name_plural': 'elements'},
        ),
        migrations.AlterField(
            model_name='element',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='icon',
            field=models.ImageField(upload_to='icons/groups/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.ImageField(upload_to='icons/groups/'),
        ),
    ]
